# Generated by Django 4.1 on 2022-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameENG', models.CharField(max_length=60)),
                ('nameBG', models.CharField(max_length=60)),
                ('monthly_upkeep', models.IntegerField()),
                ('diseases', models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('Unknown', 'Unknown')], max_length=7)),
                ('gender', models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('Unknown', 'Unknown')], max_length=7)),
                ('profile_pic', models.URLField(max_length=300)),
                ('virtual_adopter', models.CharField(max_length=60)),
                ('arrival_date', models.DateTimeField()),
                ('story_ENG', models.TextField(blank=True, null=True)),
                ('story_BG', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
