# Generated by Django 4.1 on 2022-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='nameENG',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='profile_pic',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='story_BG',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dog',
            name='story_ENG',
            field=models.TextField(blank=True, default=''),
        ),
    ]
