# Generated by Django 4.1 on 2022-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_dog_nameeng_alter_dog_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='arrival_date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='dog',
            name='diseases',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('Unknown', 'Unknown')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('Unknown', 'Unknown')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='dog',
            name='nameBG',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='virtual_adopter',
            field=models.CharField(default='', max_length=60),
        ),
    ]
