# Generated by Django 4.1 on 2022-11-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_dog_pic2_alter_dog_pic3_alter_dog_pic4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
