# Generated by Django 4.1 on 2022-11-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_people_alter_adoptions_dognameeng"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="email_address",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
