# Generated by Django 4.1 on 2022-11-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0013_people_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoptions",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="web.people",
            ),
        ),
    ]
