# Generated by Django 4.1 on 2022-11-06 03:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "web",
            "0015_rename_adoption_descriptionbg_adoptions_adoption_description_bg_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="adoptions",
            old_name="AdoptionCountryBGN",
            new_name="adoption_country_bg",
        ),
        migrations.RenameField(
            model_name="adoptions",
            old_name="AdoptionCountryENG",
            new_name="adoption_country_eng",
        ),
        migrations.RenameField(
            model_name="adoptions",
            old_name="DogNameBG",
            new_name="dog_name_bg",
        ),
    ]
