# Generated by Django 4.1 on 2022-11-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0021_rename_namebg_dog_name_bg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticeboard",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="web.people",
            ),
        ),
    ]
