# Generated by Django 4.1 on 2022-11-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_remove_noticeboard_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='web.people'),
        ),
    ]
