# Generated by Django 4.1 on 2022-11-06 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0028_alter_dog_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donations",
            name="full_name_bg",
        ),
        migrations.RemoveField(
            model_name="donations",
            name="full_name_eng",
        ),
    ]
