# Generated by Django 4.1.3 on 2022-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_adoptions_adoption_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_eng', models.TextField(blank=True, default='')),
                ('note_bg', models.TextField(blank=True, default='')),
                ('note_pic_1', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_2', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_4', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_5', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_6', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_7', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_8', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_9', models.URLField(blank=True, default='', max_length=300)),
                ('note_pic_10', models.URLField(blank=True, default='', max_length=300)),
                ('order', models.IntegerField(default=99)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='location',
            field=models.CharField(blank=True, choices=[('Gallery', 'Gallery'), ('About', 'About'), ('Infirmery', 'Infirmery'), ('Adoptions', 'Adoptions'), ('Virtual', 'Virtual'), ('Donations', 'Donations')], default='Gallery', max_length=25),
        ),
        migrations.AlterField(
            model_name='dog',
            name='active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Dead', 'Dead'), ('Adopted', 'Adopted'), ('Sick', 'Sick')], default='Active', max_length=10),
        ),
    ]
