# Generated by Django 4.1.3 on 2022-11-12 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0033_about_section_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="section_title",
            new_name="section_title_eng",
        ),
    ]
