# Generated by Django 4.1.3 on 2022-11-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0034_rename_section_title_about_section_title_eng"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="note_pic_2",
        ),
        migrations.AddField(
            model_name="about",
            name="note_p",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
    ]
