# Generated by Django 4.1.3 on 2022-11-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0038_rename_note_pic_1_about_about_pic_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="adoption_country_bg",
            field=models.CharField(default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="adoption_country_eng",
            field=models.CharField(default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="dog",
            name="adoption_year",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name="Adoptions",
        ),
    ]
