# Generated by Django 4.1.3 on 2022-11-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_donations_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
