# Generated by Django 4.1.3 on 2022-11-14 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0046_donations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donations",
            name="year_month",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
