# Generated by Django 4.1.3 on 2022-11-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0050_alter_about_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="section_desc_eng",
            field=models.TextField(blank=True, default="Info coming soon..."),
        ),
    ]
