# Generated by Django 4.1.3 on 2022-11-19 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_remove_donations_amount_remove_donations_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterField(
            model_name='donations',
            name='year_month',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 31)),
        ),
    ]
