# Generated by Django 4.1.3 on 2022-11-19 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0054_alter_donations_options_alter_donations_year_month"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donations",
            old_name="year_month",
            new_name="date",
        ),
    ]
