# Generated by Django 4.1.3 on 2022-11-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_rename_year_month_donations_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
