# Generated by Django 4.1.3 on 2022-12-15 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_dog_va_name_bg_alter_dog_va_name_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 30)),
        ),
    ]
