# Generated by Django 4.1.2 on 2022-12-13 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0060_alter_dog_va_name_bg_alter_dog_va_name_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='diseases',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N'), ('Unknown', 'Unknown')], default='', help_text='Флаг за хронични болести, например сляпота, трудно-подвижност...', max_length=7),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], default='', help_text='Пол на куче.', max_length=7),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name_bg',
            field=models.CharField(default='', help_text='Име на куче на Български.', max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name_eng',
            field=models.CharField(help_text='Име на куче на Английски.', max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='va_name_bg',
            field=models.CharField(blank=True, default='', help_text='Име на виртуален осиновител на Български.', max_length=60),
        ),
        migrations.AlterField(
            model_name='dog',
            name='va_name_eng',
            field=models.CharField(blank=True, default='', help_text='Име на виртуален осиновител на Английски.', max_length=60),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 30)),
        ),
        migrations.AlterField(
            model_name='donation',
            name='person_name_bg',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='donation',
            name='person_name_eng',
            field=models.CharField(default='', max_length=60),
        ),
    ]
