# Generated by Django 4.1.3 on 2022-12-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0061_newslettersubscriber_alter_donation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('dog', models.CharField(max_length=255)),
            ],
        ),
    ]
