# Generated by Django 4.1.2 on 2022-12-13 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0063_alter_dog_adoption_pic_after_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donation_text_eng",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Текст на дарението на Английски (за секцията със снимки на дарания).",
                    ),
                ),
                (
                    "donation_text_bg",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Текст на дарението на Български (за секцията със снимки на дарания).",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=datetime.date(2022, 11, 30),
                        help_text="Дата на дарението. По подразбиране е последният ден на предходния месец. Например ако дарението е направено на 1.01.2020, то по подразбиране ще се показва на 31.12.2019. Това е за да се показват даренията в последния месец.",
                    ),
                ),
                (
                    "donation_pic_1",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Снимка 1 в секцията.",
                        max_length=300,
                    ),
                ),
                (
                    "donation_pic_2",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Снимка 2 в секцията.",
                        max_length=300,
                    ),
                ),
                (
                    "donation_pic_3",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Снимка 3 в секцията.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "About",
            },
        ),
    ]
