# Generated by Django 4.1.2 on 2022-12-13 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0064_donationstory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donationstory",
            options={"verbose_name_plural": "DonationStories"},
        ),
    ]
