# Generated by Django 4.1.2 on 2022-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0065_alter_donationstory_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="about",
            name="photos",
            field=models.ManyToManyField(to="web.aboutphoto"),
        ),
    ]
