# Generated by Django 4.1.3 on 2022-12-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0062_adoptionform'),
        ('web', '0067_alter_about_about_pic_1_alter_about_about_pic_10_and_more'),
    ]

    operations = [
    ]
