# Generated by Django 4.1.3 on 2022-12-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_newslettersubscriber_email_newslettersubscriber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
