# Generated by Django 4.1.2 on 2022-12-22 21:05

import DogShelter.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0071_alter_newslettersubscriber_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="pic_6",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Албумна снимка.",
                max_length=300,
                validators=[DogShelter.web.validators.validate_url],
            ),
        ),
    ]
