# Generated by Django 4.1.2 on 2022-12-24 03:51

import DogShelter.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0074_donationstory_donation_pic_4_donationstory_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationstory",
            name="donation_pic_5",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Снимка 4 в секцията.",
                max_length=300,
                validators=[DogShelter.web.validators.validate_url],
            ),
        ),
        migrations.AddField(
            model_name="donationstory",
            name="donation_pic_6",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Снимка 4 в секцията.",
                max_length=300,
                validators=[DogShelter.web.validators.validate_url],
            ),
        ),
        migrations.AlterField(
            model_name="donationstory",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("high", "High")],
                default="low",
                help_text="Приоритетът ще определя сортирането на донациите и дизайнът на това как се показват. low е нисък, high е висок.",
                max_length=6,
            ),
        ),
    ]
