# Generated by Django 4.1.2 on 2022-12-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_alter_donationstory_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonationStory',
        ),
    ]
