# Generated by Django 4.1.2 on 2022-12-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0082_donationstory_title_bg_donationstory_title_eng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticeboard",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gallery", "Gallery"),
                    ("About", "About"),
                    ("Infirmery", "Infirmery"),
                    ("Adoptions", "Adoptions"),
                    ("Virtual", "Virtual"),
                    ("Donations", "Donations"),
                    ("AllDogs", "AllDogs"),
                ],
                default="Gallery",
                help_text="Място на съобщението - всяка страница разполага със способност за съобщения.",
                max_length=25,
            ),
        ),
    ]
