# Generated by Django 4.1.2 on 2022-12-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0083_alter_noticeboard_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photos',
        ),
    ]
