# Generated by Django 4.1.2 on 2022-12-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0084_remove_about_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPhoto',
        ),
    ]
