# Generated by Django 4.1.6 on 2023-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0088_rename_about_longpost_alter_longpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='visible',
            field=models.BooleanField(default=True, help_text='Скриване или показване на публикацията. Показва се по подразбиране. Променете на false, за да скриете.'),
        ),
    ]
