# Generated by Django 4.1.6 on 2023-06-19 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0100_noticeboard_flex_direction_noticeboard_note_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('subject', models.TextField(max_length=60)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 31), help_text='Дата на дарението. По подразбиране е последният ден на предходния месец. Например ако дарението е направено на 1.01.2020, то по подразбиране ще се показва на 31.12.2019. Това е за да се показват даренията в последния месец.'),
        ),
        migrations.AlterField(
            model_name='donationstory',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 31), help_text='Дата на дарението. По подразбиране е последният ден на предходния месец. Например ако дарението е направено на 1.01.2020, то по подразбиране ще се показва на 31.12.2019. Това е за да се показват даренията в последния месец.'),
        ),
    ]
