# Generated by Django 4.1.6 on 2023-06-19 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0101_contactform_alter_donation_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={"verbose_name_plural": "User messages"},
        ),
    ]
