# Generated by Django 4.1.6 on 2023-06-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0102_alter_contactform_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormModel',
        ),
    ]
